SELECT ID, NAME, DESCRIPTION, VALUE
FROM ptech.CS_ATTRIBUTE;


INSERT INTO ptech.CS_ATTRIBUTE
(ID, NAME, DESCRIPTION, VALUE)
VALUES(1001, 'brand', 'Apple brand dimension', 'Apple');
INSERT INTO ptech.CS_ATTRIBUTE
(ID, NAME, DESCRIPTION, VALUE)
VALUES(1002, 'dimensions', 'IPhone 11 dimensions H x W x D', '150.9 x 70.9 x 8.3');
INSERT INTO ptech.CS_ATTRIBUTE
(ID, NAME, DESCRIPTION, VALUE)
VALUES(1003, 'colour', 'IPhone 11 colour', 'Black');
INSERT INTO ptech.CS_ATTRIBUTE
(ID, NAME, DESCRIPTION, VALUE)
VALUES(1004, 'model', 'IPhone 11 model', 'IPhone 11');
INSERT INTO ptech.CS_ATTRIBUTE
(ID, NAME, DESCRIPTION, VALUE)
VALUES(1005, 'screen size', 'IPhone 11 screen size', '6.1"');
INSERT INTO ptech.CS_ATTRIBUTE
(ID, NAME, DESCRIPTION, VALUE)
VALUES(1006, 'colour', 'IPhone 11 colour', 'Red');
INSERT INTO ptech.CS_ATTRIBUTE
(ID, NAME, DESCRIPTION, VALUE)
VALUES(1007, 'colour', 'IPhone 11 colour', 'Green');



SELECT ID, NAME, DESCRIPTION
FROM ptech.CS_PRODUCT;

INSERT INTO ptech.CS_PRODUCT
(ID, NAME, DESCRIPTION)
VALUES(1001, 'IPhone 11', 'IPhone 11');
INSERT INTO ptech.CS_PRODUCT
(ID, NAME, DESCRIPTION)
VALUES(1002, 'IPhone 12', 'IPhone 12');
INSERT INTO ptech.CS_PRODUCT
(ID, NAME, DESCRIPTION)
VALUES(1003, 'Samsung Galaxy 10', 'Samsung Galaxy 10');
INSERT INTO ptech.CS_PRODUCT
(ID, NAME, DESCRIPTION)
VALUES(1004, 'Samsung Galaxy 10 Plus', 'Samsung Galaxy 10 Plus. Larger phone of the Galaxy 10 range.');


INSERT INTO ptech.CS_CATEGORY
(ID, NAME, DESCRIPTION)
VALUES(1001, 'Mobiles', 'Mobile Phones');
INSERT INTO ptech.CS_CATEGORY
(ID, NAME, DESCRIPTION)
VALUES(1002, 'Accessories', 'Mobiles Accessories');


INSERT INTO ptech.CS_CATEGORY_PRD
(CATEGORY_ID, SEQNUM, PRODUCT_ID)
VALUES(1001, 1, 1001);
INSERT INTO ptech.CS_CATEGORY_PRD
(CATEGORY_ID, SEQNUM, PRODUCT_ID)
VALUES(1001, 2, 1002);
INSERT INTO ptech.CS_CATEGORY_PRD
(CATEGORY_ID, SEQNUM, PRODUCT_ID)
VALUES(1001, 3, 1003);
INSERT INTO ptech.CS_CATEGORY_PRD
(CATEGORY_ID, SEQNUM, PRODUCT_ID)
VALUES(1001, 4, 1004);




